# Generated by Django 5.0.3 on 2024-03-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='movie',
            name='user_rating',
            field=models.FloatField(default='0'),
        ),
    ]
