# Generated by Django 5.0.3 on 2024-04-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_director_alter_movie_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='movie_covers/'),
        ),
    ]
